### ISSUE TITLE
Are you still interested in OpenACC?

### ISSUE THREAD

**Issue by triuk** [nachovizzo/saxpy_openacc_cpp#1]
Hi, I just raised a topic at [StackOverflow](https://stackoverflow.com/questions/77530886/openacc-c-gcc-g-complete-example) and mentioned your git. Your example was the most complete I've found so far. Could you contribute, or elaborate your code, if you are still active? I'd really appreciate it. Thanks!

**Comment by nachovizzo** [comment]
Hi thanks for the interest. But sadly I dropped my dreams of ever using OpenACC. It's not popular at all, a few people from a small niche are using it and it's not so well supported with open source compilers like gcc or clang...
